apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://13.234.120.211
    certificate-authority: /etc/ssl/certs/ca-certificates.crt
users:
- name: my-user
  user:
    client-certificate: /etc/kubernetes/pki/client-certificate.crt
    client-key: /etc/kubernetes/pki/client-key.key
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
    namespace: my-namespace
current-context: my-context
